version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_DB=fastapi
    networks:
      - app-network

  app:
    container_name: "app"
    build:
      context: ./backend
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=fastapi
      - DB_NAME=fastapi
      - DB_PASS=fastapi
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    container_name: "frontend"
    build:
      context: ./frontend
    depends_on:
      - db
      - app
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
