"""change type of user password to string

Revision ID: d5b0d3687a9c
Revises: b7ac9ed4753c
Create Date: 2024-06-05 16:35:41.413001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5b0d3687a9c'
down_revision: Union[str, None] = 'b7ac9ed4753c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
